version: "3"
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: arm64v8/phpmyadmin
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      PMA_ARBITRARY: 1
      TZ: America/New_York