---

- hosts: all

  tasks:

    - name: sudo
      apt:
        name: sudo
        update_cache: yes
        cache_valid_time: 3600
        state: latest

    - name: create user
      user:
        name: goug76
        password: "{{pwd}}"
        groups: sudo
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/goug76
    
    - name: add ssh key
      authorized_key:
        user: goug76
        key: "{{ssh_key}}"

# Password can't be plain text so run this command to hash it: mkpasswd --method=sha-512