- hosts: all

  become: yes
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Check if reboot required pi
      stat:
        path: /var/run/needrestart
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true