version: "3"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    volumes:
      - /home/${USER}/homer/assets/:/www/assets
    ports:
      - 8085:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default